"""SaldeoSMART MCP server."""

from .client import ItemError, SaldeoClient, SaldeoConfig, SaldeoError
from .models import (
    BankAccount,
    BankOperation,
    BankStatement,
    BankStatementList,
    Company,
    CompanyList,
    Contractor,
    ContractorList,
    Document,
    DocumentIdGroups,
    DocumentItem,
    DocumentList,
    DocumentPolicy,
    Employee,
    EmployeeList,
    ErrorResponse,
    InvoiceIdGroups,
    InvoiceList,
    ItemErrorPayload,
    PersonnelDocument,
    PersonnelDocumentList,
)

__all__ = [
    "BankAccount",
    "BankOperation",
    "BankStatement",
    "BankStatementList",
    "Company",
    "CompanyList",
    "Contractor",
    "ContractorList",
    "Document",
    "DocumentIdGroups",
    "DocumentItem",
    "DocumentList",
    "DocumentPolicy",
    "Employee",
    "EmployeeList",
    "ErrorResponse",
    "InvoiceIdGroups",
    "InvoiceList",
    "ItemError",
    "ItemErrorPayload",
    "PersonnelDocument",
    "PersonnelDocumentList",
    "SaldeoClient",
    "SaldeoConfig",
    "SaldeoError",
]
__version__ = "0.1.0"
