"""Pydantic models for everything that crosses the MCP boundary as JSON.

Organized by Saldeo resource family. Each submodule owns the read response
models, the input models, and any helpers exclusive to that family.
The cross-cutting error models (``ItemErrorPayload`` / ``ErrorResponse`` /
``MergeResult``) live in ``saldeosmart_mcp.errors`` and are re-exported here
so the ``saldeosmart_mcp.models`` namespace is the single public face.
"""

from __future__ import annotations

from ..errors import ErrorResponse, ItemError, ItemErrorPayload, MergeResult
from ..http.attachments import Attachment
from .accounting_close import (
    AssuranceCompanyDetailsInput,
    AssuranceDetailsInput,
    AssuranceEmployeesDetailsInput,
    AssuranceItemInput,
    AssurancePartnerDetailsInput,
    AssurancePersonalDetailsInput,
    AssuranceRenewInput,
    CloseAttachmentInput,
    CloseAttachmentType,
    DeclarationMergeInput,
    DeclarationTaxInput,
    PeriodType,
    PersonIdType,
    TaxDetailsInput,
)
from .bank import BankOperation, BankStatement, BankStatementList
from .catalog import (
    ArticleInput,
    CategoryInput,
    DescriptionInput,
    DimensionInput,
    DimensionValueInput,
    FeeInput,
    ForeignCodeInput,
    PaymentMethodInput,
    RegisterInput,
)
from .common import BankAccount, BankAccountInput
from .companies import Company, CompanyList, CompanySynchronizeInput
from .contractors import Contractor, ContractorInput, ContractorList
from .documents import (
    ContractorAreaType,
    Document,
    DocumentAddInput,
    DocumentAddRecognizeInput,
    DocumentAddRecognizeResult,
    DocumentCorrectContractorInput,
    DocumentCorrectInput,
    DocumentDimensionInput,
    DocumentDimensionValueInput,
    DocumentIdGroups,
    DocumentImportAttachmentInput,
    DocumentImportCurrencyInput,
    DocumentImportDimensionInput,
    DocumentImportInput,
    DocumentImportLineItemInput,
    DocumentImportNoVATInput,
    DocumentImportNoVATItemInput,
    DocumentImportPaymentInput,
    DocumentImportTypeInput,
    DocumentImportVATInput,
    DocumentImportVATItemInput,
    DocumentImportVATRegistryInput,
    DocumentItem,
    DocumentList,
    DocumentModelType,
    DocumentPolicy,
    DocumentSyncInput,
    DocumentUpdateInput,
    RecognizeOptionInput,
    SplitMode,
)
from .financial_balance import FinancialBalanceMergeInput, FinancialBalanceVATInput
from .invoices import InvoiceIdGroups, InvoiceList
from .personnel import (
    ContractType,
    Employee,
    EmployeeAddInput,
    EmployeeContractInput,
    EmployeeList,
    PersonnelDocument,
    PersonnelDocumentAddInput,
    PersonnelDocumentList,
    PersonnelDocumentType,
)

__all__ = [
    "ArticleInput",
    "AssuranceCompanyDetailsInput",
    "AssuranceDetailsInput",
    "AssuranceEmployeesDetailsInput",
    "AssuranceItemInput",
    "AssurancePartnerDetailsInput",
    "AssurancePersonalDetailsInput",
    "AssuranceRenewInput",
    "Attachment",
    "BankAccount",
    "BankAccountInput",
    "BankOperation",
    "BankStatement",
    "BankStatementList",
    "CategoryInput",
    "CloseAttachmentInput",
    "CloseAttachmentType",
    "Company",
    "CompanyList",
    "CompanySynchronizeInput",
    "Contractor",
    "ContractType",
    "ContractorAreaType",
    "ContractorInput",
    "ContractorList",
    "DeclarationMergeInput",
    "DeclarationTaxInput",
    "DescriptionInput",
    "DimensionInput",
    "DimensionValueInput",
    "Document",
    "DocumentAddInput",
    "DocumentAddRecognizeInput",
    "DocumentAddRecognizeResult",
    "DocumentCorrectContractorInput",
    "DocumentCorrectInput",
    "DocumentDimensionInput",
    "DocumentDimensionValueInput",
    "DocumentIdGroups",
    "DocumentImportAttachmentInput",
    "DocumentImportCurrencyInput",
    "DocumentImportDimensionInput",
    "DocumentImportInput",
    "DocumentImportLineItemInput",
    "DocumentImportNoVATInput",
    "DocumentImportNoVATItemInput",
    "DocumentImportPaymentInput",
    "DocumentImportTypeInput",
    "DocumentImportVATInput",
    "DocumentImportVATItemInput",
    "DocumentImportVATRegistryInput",
    "DocumentItem",
    "DocumentList",
    "DocumentModelType",
    "DocumentPolicy",
    "DocumentSyncInput",
    "DocumentUpdateInput",
    "Employee",
    "EmployeeAddInput",
    "EmployeeContractInput",
    "EmployeeList",
    "ErrorResponse",
    "FeeInput",
    "FinancialBalanceMergeInput",
    "FinancialBalanceVATInput",
    "ForeignCodeInput",
    "InvoiceIdGroups",
    "InvoiceList",
    "ItemError",
    "ItemErrorPayload",
    "MergeResult",
    "PaymentMethodInput",
    "PeriodType",
    "PersonIdType",
    "PersonnelDocument",
    "PersonnelDocumentAddInput",
    "PersonnelDocumentList",
    "PersonnelDocumentType",
    "RecognizeOptionInput",
    "RegisterInput",
    "SplitMode",
    "TaxDetailsInput",
]
